### ISSUE TITLE
Confirm all projects linked work, are not dead or repeats, and are awesome

### ISSUE THREAD

**Issue by jring-o** [LBRYFoundation/Awesome-LBRY-Projects#5]
Someone needs to make sure the list is awesome and not populated with repeat, dead, or obsolete projects. There are 3 different fastLBRY repos, for example. Do they all need to be here or is there one very active and inclusive version? I don't know.

Things also need to be checked that they are in the right category.

**Comment by kodxana** [comment]
fastLBRY has 2 major repos one is terminal based and one is GUI both are in progress but Terminal is developed faster.

**Comment by btzr-io** [comment]
LBRYlitics  Link is broken. Did someone hijacked the link 😛 ?
Nvm looks like a typo.
